name: Run Build Tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_tests:
    uses: OpenVoiceOS/gh-automations/.github/workflows/build-tests.yml@dev
    with:
      pre_install_pip: "git+https://github.com/TigreGotico/mediavocab@feat/audit-2026-05-core git+https://github.com/OpenVoiceOS/ovos-plugin-manager@feat/media-provider-plugin-type git+https://github.com/TigreGotico/tutubo@fix/migrate-off-contenttype"
      install_extras: "test"
      test_path: "test/"
    secrets: inherit
